apiVersion: batch/v1
kind: Job
metadata:
  name: ycsb-cxx
spec:
  template:
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: ycsb-cxx
        image: dstath/tebis_test_bench:tebis-app
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
          - name: host-storage
            mountPath: /mnt/nvme/tebis
        command: ["/bin/sh"]
        args: ["-c", "cd build/YCSB-CXX && ./ycsb-async-tebis -w s -zookeeper zk-cs:2181"]
      volumes:
      - name: host-storage
        hostPath:
          path: /mnt/nvme/tebis
          type: DirectoryOrCreate
      restartPolicy: Never
