image: carvicsforth/ubuntu_carv:latest
variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: 1
    GIT_STRATEGY: clone
    GIT_DEPTH: 0

stages:
  - build
  - deploy

build_rdma_gcc:
  stage: build
  script:
    - mkdir -p build;cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
    - make all

build_rdma_clang:
  stage: build
  script:
    - mkdir -p build;cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10
    - make all

iwyu-report:
    stage: build
    script:
        - mkdir -p build;cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DRUN_IWYU=ON -DDISABLE_ALL_WARNINGS=ON
        - make all > make_output.txt 2&> iwyu_output.txt || echo ignoring exit code since if this job fails others will fail too > /dev/null
        - ./check-iwyu-output.py
    needs: []

cppcheck:
  stage: build
  script:
    - cppcheck --language=c . --enable=all --force --inconclusive --max-ctu-depth=1024 -iYCSB-CXX -ibuild -imicrobenchmarks -iutilities -itests -ikreon_lib --inline-suppr --suppress=missingInclude
    - cppcheck --language=c . --enable=all --force --inconclusive --max-ctu-depth=1024 -iYCSB-CXX -ibuild -imicrobenchmarks -iutilities -itests -ikreon_lib --inline-suppr --suppress=missingInclude &> log.txt
    - python scripts/CI/check-cppcheck-output.py

install_kreon:
  stage: deploy
  variables:
    KREON_INSTALL_PATH : "installtest"
  script:
    - mkdir -p build;cd build
    - cmake .. -DKREON_BUILD_CPACK=True -DCMAKE_BUILD_TYPE=Debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10
    - make install DESTDIR=$KREON_INSTALL_PATH;mv $KREON_INSTALL_PATH ../scripts/;cd ../scripts
    - ./verify-installed-files.py $KREON_INSTALL_PATH

pre-commit:
  image: carvicsforth/arch_carv:latest
  stage: build
  script:
    - ./scripts/pre-commit-CI.sh

pre-merge:
  image: carvicsforth/arch_carv:latest
  stage: build
  script:
    - ./scripts/pre-merge-CI.sh
    - ./scripts/commit-msg-lint.py
  only:
    - merge_requests
