apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-datalog-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nvme/Tebis/zookeeper/data"
