apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nvme/Tebis/zookeeper/data"
