apiVersion: apps/v1
kind: Deployment
metadata:
  name: tebis-deployment-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tebis-2
  template:
    metadata:
      labels:
        app: tebis-2
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: tebis
        image: dstath/tebis_test_bench:tebis-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        securityContext:
          privileged: true
        command: ["/bin/sh", "-c", "--"]
        args:
          - |
            if ! ip addr show | grep -q '192.168.4.1'; then
              echo "Not rdma found."
            fi
            echo "Interface setup complete. Sleeping indefinitely.";
            sleep infinity
        volumeMounts:
          - name: host-storage
            mountPath: /mnt/nvme/tebis_2
      volumes:
      - name: host-storage
        hostPath:
          path: /mnt/nvme/tebis_2
          type: DirectoryOrCreate
